services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - redis
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_REDIS_HOST: redis

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8090:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data:
